server:
  port: 8081
  servlet:
    context-path: /ferrisys-service

spring:
  application:
    name: ferrisys-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ferrisys_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 25000
      idle-timeout: 50000
      max-lifetime: 1800000
      keepalive-time: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:Z3nU52@93xDklq902hAs78bLcNjsL29cHSsA9kPmsJq9kdPoaVq}

modules:
  inventory:
    enabled: true
  purchases:
    enabled: true
  clients:
    enabled: true
  providers:
    enabled: true
  quotes:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

app:
  tenant:
    allow-header-fallback: false
